@startuml AITokenAnalyzer

interface ITokenizer {
    +OutputTokens(text: string): vector<string>
}

class Tokenizer {
    +OutputTokens(text: string): vector<string>
}

interface ICostCalculator {
    +CalculateCost(total_tokens: int, mcl: int, tps: int): float
}

class CostCalculator {
    +CalculateCost(total_tokens: int, mcl: int, tps: int): float
}

interface IModelParams {
    -MAX_CONTENT_LENGTH: int
    -TOKENS_PER_SECOND: int
}

class ModelParams {
    -MAX_CONTENT_LENGTH: int
    -TOKENS_PER_SECOND: int
}

class ConfigIO {
    +load_config(path: string): vector<ModelsParams>
    +load_models(path: string): vector<string>
}

class UnitConverter {
    +w_to_kwh(watts: float): float
    +kwh_to_w(kwh: float): float
    +convert_currency(conversion_func: void *, price: float): float
}

class Main {
    - calc: CostCalculator
    - tb: Tokenizer
    - conf: ConfigIO
}

' Relationship's
' Tokenizer Relationships
ITokenizer ..|> Tokenizer
' Cost Algo. Relationships
ICostCalculator ..|> CostCalculator
CostCalculator --> UnitConverter
' Model/Config Relationships
IModelParams ..|> ModelParams
ConfigIO --> ModelParams
' Main relationships
CostCalculator --> Main
Tokenizer --> Main
ConfigIO --> Main
@enduml